# Main information for blog creation
title: vladd12's Blog
email: vladd12z32@gmail.com
description: >- # this means to ignore newlines
  Блог начинающего программиста о программировании 🤡

# GitHub Pages settings
repository: vladd12/vladd12.github.io             # Need by GitHub Pages for short time
github_username: vladd12                      # GitHub username
domain: vladd12.github.io                     # domain for site (need by GitHub Pages)
url: https://vladd12.github.io/  # the base hostname and protocol for site
lsi: false
safe: true

# Incremental build disabling
incremental: false

# Highlight settings
highlighter: rouge
gist:
  noscript: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
# kramdown usage: 
# 1) https://prgssr.ru/articles/osobennosti-sintaksisa-kramdown-chast-1.html
# 2) https://devhints.io/kramdown
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Footer settings
author: vladd12
copyright: '2022'

# Sharing blog
share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

# Social nets
social:
  github: vladd12
  stackoverflow: vladd12
  stackoverflow_id: 17157999
  #linkedin: ''
  #rss: feed.xml

sass:
  style: compressed

# Google Analytics key
#google_analytics_key:

# Yandex metrica (https://metrica.yandex.com/)
#yandex_metrica:

# Disqus comments settings
disqus: vladd12z32
comments: false

# Exclude files from processing
exclude:
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - Instructions.txt
