
title: vladd12 Blog
email: vladd12z32@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username:  vladd12

repository: vladd12/gh-pages-test
domain: vladd12.github.io                     # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://vladd12.github.io/gh-pages-test  # the base hostname and protocol for your site, e.g. http://example.com
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Build settings (theme and plugins)
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
